### ISSUE TITLE
Incorrect authentication credentials

### ISSUE THREAD

**Issue by IsaacHatilima** [CryceTruly/contactListApp#2]
Hi, 
I followed you tutorial on youtube but I am getting Incorrect authentication credentials when I try to send the token as Bearer in postman.

**Comment by samuel025** [comment]
In the authentication views, change the auth_token to 
```auth_token = jwt.encode({'username': user.username}, settings.JWT_SECRET_KEY, algorithm='HS256'```



While in the backend.py file, add 
```
algorithms ="HS256"
```
To the auth_token
